[all]
vm1 ansible_host=172.30.0.11
vm2 ansible_host=172.30.0.12
vm3 ansible_host=172.30.0.13

[all:vars]
ansible_user=devops
ansible_ssh_private_key_file=/home/ittth/.ssh/v7_devops_key
ansible_python_interpreter=/usr/bin/python3
